"""Add Phase 1 inventory management tables

Revision ID: eb237c60beaf
Revises: 003_rename_auth_fields
Create Date: 2025-10-10 20:31:32.026295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb237c60beaf'
down_revision: Union[str, Sequence[str], None] = '003_rename_auth_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_types',
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('type_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('HARVEST', 'MEAT', 'POULTRY', 'PACKAGING', 'SUPPLIES', 'OTHER', name='inventorycategoryenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('perishable', sa.Boolean(), nullable=False),
    sa.Column('typical_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_types_account_id'), 'inventory_types', ['account_id'], unique=False)
    op.create_index(op.f('ix_inventory_types_category'), 'inventory_types', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_types_id'), 'inventory_types', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_types_type_name'), 'inventory_types', ['type_name'], unique=False)
    op.create_table('warehouses',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('storage_capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('temperature_controlled', sa.Boolean(), nullable=False),
    sa.Column('min_temperature', sa.Float(), nullable=True),
    sa.Column('max_temperature', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_account_id'), 'warehouses', ['account_id'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_warehouse_code'), 'warehouses', ['warehouse_code'], unique=False)
    op.create_table('storage_bins',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('bin_name', sa.String(length=255), nullable=False),
    sa.Column('bin_code', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('capacity_unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_bins_bin_code'), 'storage_bins', ['bin_code'], unique=False)
    op.create_index(op.f('ix_storage_bins_id'), 'storage_bins', ['id'], unique=False)
    op.create_index(op.f('ix_storage_bins_warehouse_id'), 'storage_bins', ['warehouse_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('inventory_type_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('current_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('minimum_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('lot_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', 'EXPIRED', 'DAMAGED', 'IN_TRANSIT', name='inventorystatusenum'), nullable=False),
    sa.Column('related_crop_id', sa.Integer(), nullable=True),
    sa.Column('related_animal_id', sa.Integer(), nullable=True),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bin_id'], ['storage_bins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_type_id'], ['inventory_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_account_id'), 'inventory_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_batch_number'), 'inventory_items', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_items_bin_id'), 'inventory_items', ['bin_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_expiry_date'), 'inventory_items', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_items_inventory_type_id'), 'inventory_items', ['inventory_type_id'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_name'), 'inventory_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_inventory_items_lot_number'), 'inventory_items', ['lot_number'], unique=False)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=False)
    op.create_index(op.f('ix_inventory_items_status'), 'inventory_items', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_items_warehouse_id'), 'inventory_items', ['warehouse_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('ADD', 'REMOVE', 'ADJUSTMENT', 'TRANSFER', 'SALE', 'SPOILAGE', 'RETURN', name='transactiontypeenum'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_before', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantity_after', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.Column('performed_by_account_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transaction_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_location_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_location_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_inventory_item_id'), 'inventory_transactions', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_performed_by_account_id'), 'inventory_transactions', ['performed_by_account_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_date'), 'inventory_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    op.drop_index(op.f('idx_account_roles_account'), table_name='account_roles')
    op.drop_index(op.f('idx_account_roles_role'), table_name='account_roles')
    op.drop_index(op.f('idx_accounts_active_verified'), table_name='accounts')
    op.drop_index(op.f('idx_accounts_deleted'), table_name='accounts')
    op.drop_index(op.f('idx_accounts_type_status'), table_name='accounts')
    op.drop_index(op.f('idx_business_categories_gin'), table_name='business_profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_farmer_certifications_gin'), table_name='farmer_profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_farmer_crop_types_gin'), table_name='farmer_profiles', postgresql_using='gin')
    op.drop_index(op.f('idx_role_permissions_gin'), table_name='roles', postgresql_using='gin')
    op.drop_index(op.f('idx_verification_account_type'), table_name='verification_records')
    op.drop_index(op.f('idx_verification_status'), table_name='verification_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_verification_status'), 'verification_records', ['status'], unique=False)
    op.create_index(op.f('idx_verification_account_type'), 'verification_records', ['account_id', 'verification_type'], unique=False)
    op.create_index(op.f('idx_role_permissions_gin'), 'roles', ['permissions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_farmer_crop_types_gin'), 'farmer_profiles', ['crop_types'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_farmer_certifications_gin'), 'farmer_profiles', ['certifications'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_business_categories_gin'), 'business_profiles', ['business_categories'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_accounts_type_status'), 'accounts', ['account_type', 'status'], unique=False)
    op.create_index(op.f('idx_accounts_deleted'), 'accounts', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_accounts_active_verified'), 'accounts', ['is_active', 'is_verified'], unique=False)
    op.create_index(op.f('idx_account_roles_role'), 'account_roles', ['role_id'], unique=False)
    op.create_index(op.f('idx_account_roles_account'), 'account_roles', ['account_id'], unique=False)
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_transaction_date'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_performed_by_account_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_inventory_item_id'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_items_warehouse_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_status'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_lot_number'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_inventory_type_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_expiry_date'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_bin_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_batch_number'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_account_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_storage_bins_warehouse_id'), table_name='storage_bins')
    op.drop_index(op.f('ix_storage_bins_id'), table_name='storage_bins')
    op.drop_index(op.f('ix_storage_bins_bin_code'), table_name='storage_bins')
    op.drop_table('storage_bins')
    op.drop_index(op.f('ix_warehouses_warehouse_code'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_account_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_inventory_types_type_name'), table_name='inventory_types')
    op.drop_index(op.f('ix_inventory_types_id'), table_name='inventory_types')
    op.drop_index(op.f('ix_inventory_types_category'), table_name='inventory_types')
    op.drop_index(op.f('ix_inventory_types_account_id'), table_name='inventory_types')
    op.drop_table('inventory_types')
    # ### end Alembic commands ###
